from typing import TypedDict, List
from langchain_core.documents import Document
from pydantic import BaseModel


# state for the agent
class RAGState(TypedDict):
    query: str
    retrieved_docs: List[Document]
    reranked_docs: List[Document]
    response: dict
    route: str  # vector_db or rdbms
    generated_sql: str  # sql generated by nl2sql
    sql_result: str  # output of the raw sql execution result
    vector_context: str
    sql_context: str
    final_context: str
    evaluation: str
    retry_count: int    
    evaluation_feedback: str